name: env_iwfm

channels:
  - defaults
  - conda-forge
 
dependencies:
  #basics
  - python
  - pip
  - ipykernel
  - autopep8
  #data
  - pandas
  - xarray
  - scikit-learn
  - statsmodels
  - dask
  - numba
  #visualization
  - pyepsg
  - geopandas
  - holoviews 
  - hvplot
  - matplotlib
  - bokeh
  - geoviews
  - ipyleaflet
  - spatialpandas
